# Default values for modernpets.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: registry.ng.bluemix.net/modernpets # Ex: registry.ng.bluemix.net/mynamespace
  pullPolicy: Always

web:
  image:
    tag: latest
db:
  image:
    tag: latest

ingress:
  enabled: true
  hosts:
    - jpetstore.argodc.us-east.containers.appdomain.cloud # Ex: jpetstore.myclustername.us-south.containers.mybluemix.net