# Default values for modernpets.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: mycluster.icp:8500/jpetstore
  pullPolicy: Always

web:
  image:
    tag: latest
db:
  image:
    tag: latest

ingress:
  enabled: true
  hosts:
    - mycluster.icp